name: Push Docker Image to ECR

on:
  push:
    branches:
      - master

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 631208496322.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build, Tag, and Push Docker Image
        run: |
          docker build -t docker_image_demo .
          docker tag docker_image_demo:latest 631208496322.dkr.ecr.ap-south-1.amazonaws.com/ayeman/poc:latest
          docker push 631208496322.dkr.ecr.ap-south-1.amazonaws.com/ayeman/poc:latest
